#!/bin/bash

# update rails board
cd ~/ruby/rails && git fetch && cd ~/projects/gittop
./gittop /Users/yankov/ruby/rails -f rails_boards.js && mv rails_boards.js ~/projects/gitboards/js/

cd ~/projects/metasploit-framework && git fetch && cd ~/projects/gittop
./gittop /Users/yankov/projects/metasploit-framework -f metasploit_boards.js && mv metasploit_boards.js ~/projects/gitboards/js/

cd ~/projects/gitboards
git commit -a -m "update boards"
git push origin gh-pages
cd ~/projects/gittop





